name: Canary Release

on:
  pull_request:
    branches:
      - main

jobs:
  release-canary:
    uses: the-guild-org/shared-config/.github/workflows/release-snapshot.yml@main
    with:
      packageManager: pnpm
      nodeVersion: 16 # align with the-guild-org/changesets-snapshot-action
      npmTag: canary
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NPM_TOKEN }}
